pretrained_model:
  folds:
    1:     
      train: ["3", "5", "7", "11", "13", "15", "19", "21", "X", "chr3", "chr5", "chr7", "chr11", "chr13", "chr15", "chr19", "chr21", "chrX"]
      val: ["1", "9", "17","chr1", "chr9", "chr17"]
      test: []
      transfer_checkpoint: 50perc_06_23_f1.ckpt
    2:
      train: ["2", "6", "8", "10", "14", "16", "18", "22", "Y", "chr2", "chr6", "chr8", "chr10", "chr14", "chr16", "chr18", "chr22", "chrY"]
      val: ["4", "12", "20", "chr4", "chr12", "chr20"]
      test: ["1", "3", "5", "7", "9", "11", "13", "15", "17", "19", "21", "X", "chr1", "chr3", "chr5", "chr7", "chr9", "chr11", "chr13", "chr15", "chr17", "chr19", "chr21", "chrX"]
      transfer_checkpoint: 50perc_06_23_f2.ckpt
patience: 1
seq : false
lr: 0.0008
